name: CI-CD Level Devil Webapp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXUS_URL: "http://3.17.13.134:8081/repository/maven-snapshots/"
      GROUP_ID_PATH: "com/example"
      APP_NAME: "level-devil-webapp"
      DOCKER_REPO: "sgorijala513/tomcat"

    steps:
      # === Checkout Code (same as Jenkins 'Checkout Code' stage) ===
      - name: Checkout code
        uses: actions/checkout@v4

      # === Setup Java (needed for Maven build) ===
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # === Show Commit SHA (similar to echo GIT_COMMIT) ===
      - name: Show commit
        run: echo "Commit: $GITHUB_SHA"

      # === SonarQube Analysis (similar to 'SonarQube Analysis' stage) ===
      - name: SonarQube analysis
        env:
          SONAR_HOST_ULR: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.projectKey=level-devil-webapp \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # === SonarQube Quality Gate (approx. Jenkins waitForQualityGate) ===
      # NOTE: this uses SonarQube GitHub Action to wait for quality gate result.
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_ULR: ${{ secrets.SONAR_HOST_URL }}

      # === Build WAR (same as 'Build WAR' stage) ===
      - name: Build WAR
        run: mvn -B clean package -DskipTests=false

      # === Upload WAR to Nexus (same logic as Jenkins) ===
      - name: Upload WAR to Nexus
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          WAR=$(ls target/*.war | head -n 1)
          VERSION=$(grep -m1 "<version>" pom.xml | sed 's|.*<version>||; s|</version>.*||')
          ARTIFACT_URL="${NEXUS_URL}${GROUP_ID_PATH}/${APP_NAME}/${VERSION}/${APP_NAME}-${VERSION}.war"

          echo "WAR file: $WAR"
          echo "VERSION: $VERSION"
          echo "Uploading WAR → $ARTIFACT_URL"

          curl -u "${NEXUS_USER}:${NEXUS_PASS}" \
               --upload-file "${WAR}" \
               "${ARTIFACT_URL}"

      # === Login to Docker Hub (before build+push) ===
      - name: Docker Hub login
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      # === Build Docker Image (same as 'Build Docker Image' stage) ===
      - name: Build Docker image
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          VERSION=$(grep -m1 "<version>" pom.xml | sed 's|.*<version>||; s|</version>.*||')
          SHORT_SHA=${GITHUB_SHA::7}

          echo "Building docker image with VERSION=${VERSION}, TAG=${SHORT_SHA}"

          docker build \
            --build-arg NEXUS_URL=${NEXUS_URL} \
            --build-arg GROUP_ID_PATH=${GROUP_ID_PATH} \
            --build-arg APP_NAME=${APP_NAME} \
            --build-arg VERSION=${VERSION} \
            --build-arg NEXUS_USER=${NEXUS_USER} \
            --build-arg NEXUS_PASS=${NEXUS_PASS} \
            -t ${DOCKER_REPO}:${SHORT_SHA} \
            -t ${DOCKER_REPO}:latest \
            .

      # === Push Docker Image (same as 'Push Docker Image' stage) ===
      - name: Push Docker image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker push ${DOCKER_REPO}:${SHORT_SHA}
          docker push ${DOCKER_REPO}:latest

      # === Deploy to Tomcat Docker Server (same as Jenkins SSH deploy) ===
      - name: Deploy to Tomcat Docker Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.17.13.134
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${DOCKER_REPO}:latest
            docker stop tomcat 2>/dev/null || true
            docker rm tomcat 2>/dev/null || true
            docker run -d --name tomcat -p 8080:8080 ${DOCKER_REPO}:latest
